spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: sa
    password: 1


  jpa:
    properties:
      hibernate:
        format_sql: true
        user_sql_comments: true

    hibernate:
      ddl-auto: create

logging:
  level:
    org:
      apache:
        coyote:
          http11: debug

      hibernate:
        SQL: debug

    board:
      myboard: info